language: node_js
node_js: stable
install:
- npm install
script:
- npm run unit
- npm run e2e
- npm run server
after_script:
- rm -rf node_modules
- scp -o stricthostkeychecking=no  -r ./* root@140.143.202.200:/usr/share/nginx/html/test
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_adfd768a7744_key -iv $encrypted_adfd768a7744_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 140.143.202.200
